import type { DrugDossier } from '@shared/types'

const keytruda: DrugDossier = {
  drug: {
    id: 'pembrolizumab',
    name: 'Pembrolizumab',
    genericName: 'pembrolizumab',
    brandName: 'Keytruda',
    manufacturer: 'Merck',
    status: 'Approved',
  },

  summary: {
    description:
      'Keytruda (pembrolizumab) is a PD-1 checkpoint inhibitor monoclonal antibody approved across 20+ oncology indications. Originally approved for melanoma in 2014, it has since expanded into lung, head and neck, bladder, gastric, and tissue-agnostic indications — becoming one of the most prescribed immuno-oncology agents globally.',
    mechanism: 'PD-1 (Programmed Death-1) checkpoint inhibitor',
    target: 'PD-1',
  },

  evidence: [
    {
      id: 'ev-001',
      sourceType: 'fda',
      title: 'KEYTRUDA (pembrolizumab) Prescribing Information',
      publisher: 'FDA',
      url: 'https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/125514s118lbl.pdf',
      date: '2023-10-05',
      excerpt:
        'KEYTRUDA is a programmed death receptor-1 (PD-1)–blocking antibody indicated for the treatment of patients with unresectable or metastatic melanoma.',
      authority: 'primary',
    },
    {
      id: 'ev-002',
      sourceType: 'clinicaltrials',
      title: 'KEYNOTE-001: Study of Pembrolizumab in Participants With Advanced Solid Tumors',
      publisher: 'ClinicalTrials.gov',
      url: 'https://clinicaltrials.gov/study/NCT01295827',
      date: '2011-02-14',
      authority: 'primary',
    },
    {
      id: 'ev-003',
      sourceType: 'clinicaltrials',
      title: 'KEYNOTE-119: Pembrolizumab Versus Chemotherapy in Previously Treated Metastatic TNBC',
      publisher: 'ClinicalTrials.gov',
      url: 'https://clinicaltrials.gov/study/NCT02555657',
      date: '2015-09-21',
      authority: 'primary',
    },
    {
      id: 'ev-004',
      sourceType: 'sponsor',
      title: 'Merck Provides Update on KEYNOTE-119 — Phase 3 Trial of Keytruda in mTNBC',
      publisher: 'Merck & Co.',
      url: 'https://www.merck.com/news/merck-provides-update-on-keynote-119',
      date: '2019-10-01',
      excerpt:
        'Keytruda did not meet the primary endpoint of overall survival in the KEYNOTE-119 trial in patients with previously treated metastatic triple-negative breast cancer.',
      authority: 'secondary',
    },
    {
      id: 'ev-005',
      sourceType: 'fda',
      title: 'FDA Approval Letter — Accelerated Approval for Unresectable Melanoma',
      publisher: 'FDA',
      url: 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2014/125514Orig1s000ltr.pdf',
      date: '2014-09-04',
      authority: 'primary',
    },
    {
      id: 'ev-006',
      sourceType: 'publication',
      title:
        'Pembrolizumab versus Ipilimumab in Advanced Melanoma (KEYNOTE-006)',
      publisher: 'New England Journal of Medicine',
      url: 'https://www.nejm.org/doi/10.1056/NEJMoa1503093',
      date: '2015-04-19',
      authority: 'secondary',
    },
    {
      id: 'ev-007',
      sourceType: 'clinicaltrials',
      title: 'KEYNOTE-024: Pembrolizumab vs. Platinum-Based Chemotherapy in NSCLC (PD-L1 ≥50%)',
      publisher: 'ClinicalTrials.gov',
      url: 'https://clinicaltrials.gov/study/NCT02142738',
      date: '2014-05-19',
      authority: 'primary',
    },
  ],

  findings: [
    {
      id: 'f-001',
      title: 'Phase III Setback in Breast Cancer',
      category: 'development',
      severity: 'high',
      summary:
        'KEYNOTE-119 failed to improve overall survival with pembrolizumab monotherapy vs. chemotherapy in previously treated metastatic TNBC. Merck subsequently pivoted to a combination strategy (KEYNOTE-522 / KEYNOTE-355) that achieved FDA approval.',
      evidenceIds: ['ev-003', 'ev-004'],
      confidence: 'secondary',
      reviewStatus: 'unreviewed',
      targetTab: 'history',
    },
    {
      id: 'f-002',
      title: 'Crowded PD-1/PD-L1 Mechanism Landscape',
      category: 'network',
      severity: 'info',
      summary:
        'At least 6 approved therapies target the PD-1/PD-L1 checkpoint pathway. Pembrolizumab competes directly with nivolumab (PD-1), atezolizumab, and durvalumab (PD-L1) across multiple shared oncology indications.',
      evidenceIds: ['ev-001'],
      confidence: 'primary',
      reviewStatus: 'unreviewed',
      targetTab: 'network',
    },
    {
      id: 'f-003',
      title: 'Biomarker-Driven Expansion Strategy',
      category: 'regulatory',
      severity: 'info',
      summary:
        "Keytruda's approval history reflects a systematic PD-L1 and TMB biomarker-driven expansion — from melanoma in 2014 to a tissue-agnostic TMB-high approval in 2019, covering any solid tumor with ≥10 mutations/Mb regardless of histology.",
      evidenceIds: ['ev-001', 'ev-005'],
      confidence: 'primary',
      reviewStatus: 'unreviewed',
      targetTab: 'label',
    },
    {
      id: 'f-004',
      title: 'Immune-Mediated Adverse Reaction Warning',
      category: 'label',
      severity: 'medium',
      summary:
        'The FDA label carries prominent warnings for immune-mediated adverse reactions that can be severe or fatal — including pneumonitis, colitis, hepatitis, and endocrinopathies. This is a class effect shared by all checkpoint inhibitors.',
      evidenceIds: ['ev-001'],
      confidence: 'primary',
      reviewStatus: 'unreviewed',
      targetTab: 'label',
    },
  ],

  label: {
    indications: [
      'Unresectable or metastatic melanoma',
      'Adjuvant treatment of melanoma with lymph node involvement',
      'First-line metastatic NSCLC (PD-L1 ≥1%, no EGFR/ALK)',
      'Metastatic NSCLC — combination with platinum chemotherapy',
      'Resectable NSCLC — neoadjuvant + adjuvant',
      'Recurrent or metastatic HNSCC (PD-L1 CPS ≥1)',
      'Classical Hodgkin lymphoma (relapsed/refractory)',
      'Urothelial carcinoma (cisplatin-ineligible or progressive)',
      'MSI-H/dMMR cancer — tumor agnostic',
      'Gastric or GEJ adenocarcinoma (PD-L1 CPS ≥1)',
      'Esophageal cancer (PD-L1 CPS ≥10)',
      'Cervical cancer (PD-L1 CPS ≥1)',
      'Hepatocellular carcinoma (sorafenib-treated)',
      'Merkel cell carcinoma (recurrent locally advanced or metastatic)',
      'TMB-high solid tumors — tumor agnostic (≥10 mut/Mb)',
      'Colorectal cancer (MSI-H/dMMR, second-line)',
      'Endometrial carcinoma (MSI-H/dMMR or combination)',
      'Biliary tract cancer — combination',
      'Triple-negative breast cancer — combination (early-stage)',
      'Metastatic TNBC (PD-L1 CPS ≥10)',
    ],
    mechanism:
      'Pembrolizumab is a humanized monoclonal antibody that blocks the interaction between PD-1 and its ligands, PD-L1 and PD-L2. By blocking this interaction, pembrolizumab releases PD-1 pathway–mediated inhibition of the immune response, including anti-tumor immune response.',
    target: 'PD-1 (Programmed Death-1)',
    warnings: [
      'Immune-mediated adverse reactions — can occur in any organ and may be severe or fatal; includes pneumonitis, colitis, hepatitis, endocrinopathies, nephritis, and skin adverse reactions',
      'Infusion-related reactions — severe or life-threatening reactions have been reported',
      'Complications of allogeneic HSCT — fatal and serious complications reported in patients who received HSCT before or after pembrolizumab',
      'Embryo-fetal toxicity — can cause fetal harm based on mechanism of action; advise females of reproductive potential to use effective contraception',
    ],
    adverseReactions: [
      'Fatigue',
      'Musculoskeletal pain',
      'Decreased appetite',
      'Pruritus',
      'Diarrhea',
      'Nausea',
      'Rash',
      'Pyrexia',
      'Cough',
      'Dyspnea',
      'Constipation',
      'Hypothyroidism',
      'Anemia',
      'Peripheral edema',
      'Abdominal pain',
    ],
    evidenceIds: ['ev-001'],
  },

  network: {
    nodes: [
      {
        id: 'pembrolizumab',
        name: 'Pembrolizumab',
        brandName: 'Keytruda',
        genericName: 'pembrolizumab',
        target: 'PD-1',
        mechanism: 'PD-1 checkpoint inhibitor',
        status: 'Approved',
        sharedIndications: [],
        evidenceIds: ['ev-001'],
      },
      {
        id: 'nivolumab',
        name: 'Nivolumab',
        brandName: 'Opdivo',
        genericName: 'nivolumab',
        target: 'PD-1',
        mechanism: 'PD-1 checkpoint inhibitor',
        status: 'Approved',
        sharedIndications: ['Melanoma', 'NSCLC', 'RCC', 'Colorectal cancer'],
        evidenceIds: ['ev-001'],
      },
      {
        id: 'cemiplimab',
        name: 'Cemiplimab',
        brandName: 'Libtayo',
        genericName: 'cemiplimab',
        target: 'PD-1',
        mechanism: 'PD-1 checkpoint inhibitor',
        status: 'Approved',
        sharedIndications: ['NSCLC', 'Cervical cancer'],
        evidenceIds: ['ev-001'],
      },
      {
        id: 'dostarlimab',
        name: 'Dostarlimab',
        brandName: 'Jemperli',
        genericName: 'dostarlimab',
        target: 'PD-1',
        mechanism: 'PD-1 checkpoint inhibitor',
        status: 'Approved',
        sharedIndications: ['Endometrial cancer', 'dMMR solid tumors'],
        evidenceIds: ['ev-001'],
      },
      {
        id: 'atezolizumab',
        name: 'Atezolizumab',
        brandName: 'Tecentriq',
        genericName: 'atezolizumab',
        target: 'PD-L1',
        mechanism: 'PD-L1 checkpoint inhibitor',
        status: 'Approved',
        sharedIndications: ['NSCLC', 'TNBC', 'Urothelial carcinoma'],
        evidenceIds: ['ev-001'],
      },
      {
        id: 'durvalumab',
        name: 'Durvalumab',
        brandName: 'Imfinzi',
        genericName: 'durvalumab',
        target: 'PD-L1',
        mechanism: 'PD-L1 checkpoint inhibitor',
        status: 'Approved',
        sharedIndications: ['NSCLC', 'Biliary tract cancer'],
        evidenceIds: ['ev-001'],
      },
      {
        id: 'ipilimumab',
        name: 'Ipilimumab',
        brandName: 'Yervoy',
        genericName: 'ipilimumab',
        target: 'CTLA-4',
        mechanism: 'CTLA-4 checkpoint inhibitor',
        status: 'Approved',
        sharedIndications: ['Melanoma', 'NSCLC', 'RCC'],
        evidenceIds: ['ev-001'],
      },
    ],
    edges: [
      { id: 'e-001', source: 'pembrolizumab', target: 'nivolumab', relationship: 'same_target' },
      { id: 'e-002', source: 'pembrolizumab', target: 'cemiplimab', relationship: 'same_target' },
      { id: 'e-003', source: 'pembrolizumab', target: 'dostarlimab', relationship: 'same_target' },
      { id: 'e-004', source: 'pembrolizumab', target: 'atezolizumab', relationship: 'same_mechanism' },
      { id: 'e-005', source: 'pembrolizumab', target: 'durvalumab', relationship: 'same_mechanism' },
      { id: 'e-006', source: 'pembrolizumab', target: 'ipilimumab', relationship: 'shared_indication' },
      { id: 'e-007', source: 'pembrolizumab', target: 'nivolumab', relationship: 'shared_indication' },
    ],
  },

  history: {
    events: [
      {
        id: 'he-001',
        year: 2011,
        date: '2011-02-14',
        title: 'Phase I first-in-human trial initiated',
        type: 'trial_started',
        summary:
          'KEYNOTE-001, the first clinical trial of pembrolizumab, began enrolling patients with advanced solid tumors. This basket trial would ultimately enroll over 1,200 patients and generate the foundational safety and efficacy data underpinning the first regulatory approval.',
        phase: 'Phase I',
        trialId: 'NCT01295827',
        evidenceIds: ['ev-002'],
        confidence: 'primary',
        importance: 'high',
      },
      {
        id: 'he-002',
        year: 2014,
        date: '2014-09-04',
        title: 'First FDA approval — accelerated approval in melanoma',
        type: 'approval',
        summary:
          'FDA granted accelerated approval for pembrolizumab in unresectable or metastatic melanoma after progression on ipilimumab — making it the first PD-1 inhibitor approved in the United States and establishing the proof-of-concept for the checkpoint inhibitor class.',
        indication: 'Unresectable or metastatic melanoma',
        evidenceIds: ['ev-001', 'ev-005'],
        confidence: 'primary',
        importance: 'high',
      },
      {
        id: 'he-003',
        year: 2016,
        date: '2016-10-24',
        title: 'First-line NSCLC approval — biomarker-selected',
        type: 'approval',
        summary:
          'FDA approved pembrolizumab as first-line therapy for metastatic NSCLC with PD-L1 expression ≥50% and no EGFR/ALK alterations (KEYNOTE-024). This was the first biomarker-selected first-line approval in lung cancer — a landmark that reshaped the standard of care.',
        indication: 'Metastatic NSCLC (PD-L1 ≥50%)',
        trialId: 'NCT02142738',
        phase: 'Phase III',
        evidenceIds: ['ev-001', 'ev-007'],
        confidence: 'primary',
        importance: 'high',
      },
      {
        id: 'he-004',
        year: 2019,
        date: '2019-10-01',
        title: 'Phase III setback — KEYNOTE-119 fails in metastatic TNBC',
        type: 'setback',
        summary:
          'KEYNOTE-119 did not meet its primary endpoint of overall survival improvement versus chemotherapy in previously treated metastatic triple-negative breast cancer. The trial compared pembrolizumab monotherapy to physician\'s choice of single-agent chemotherapy across 622 patients.',
        phase: 'Phase III',
        trialId: 'NCT02555657',
        indication: 'Metastatic triple-negative breast cancer',
        status: 'Primary endpoint not met',
        evidenceIds: ['ev-003', 'ev-004'],
        confidence: 'secondary',
        importance: 'high',
        setbackReport: {
          whatWasTested:
            'KEYNOTE-119 enrolled 622 patients with previously treated metastatic triple-negative breast cancer (mTNBC). Patients were randomized to pembrolizumab monotherapy versus physician\'s choice single-agent chemotherapy (capecitabine, eribulin, gemcitabine, or vinorelbine). The primary endpoint was overall survival, assessed in the intent-to-treat population and in PD-L1 CPS ≥1 and CPS ≥10 subgroups.',
          whatHappened:
            'Pembrolizumab monotherapy did not demonstrate a statistically significant improvement in overall survival versus chemotherapy in the ITT population (HR 0.97; 95% CI 0.82–1.15) or in the CPS ≥1 subgroup. A trend toward benefit was observed in the CPS ≥10 subgroup, but this did not reach statistical significance across all analysis timepoints.',
          publicExplanation:
            'Merck announced in October 2019 that KEYNOTE-119 did not meet its primary endpoint. Available public evidence indicates the monotherapy approach may have been insufficient in the heavily pre-treated metastatic setting, and that patient enrichment by PD-L1 status alone was not enough to identify responders. The comparator chemotherapy arm also showed higher-than-expected activity. No single authoritative mechanistic explanation has been provided by the sponsor.',
          whatHappenedNext:
            'Following the KEYNOTE-119 setback, Merck pivoted to a combination strategy. KEYNOTE-522 evaluated pembrolizumab plus neoadjuvant chemotherapy in early-stage TNBC and met its co-primary endpoints, leading to FDA approval in July 2021 for high-risk early TNBC. In the metastatic setting, KEYNOTE-355 demonstrated that pembrolizumab plus chemotherapy improved PFS and OS in PD-L1 CPS ≥10 tumors, securing approval in November 2020.',
        },
      },
      {
        id: 'he-005',
        year: 2020,
        date: '2020-11-13',
        title: 'Metastatic TNBC approval — combination strategy succeeds',
        type: 'approval',
        summary:
          'Despite the KEYNOTE-119 monotherapy setback, FDA approved pembrolizumab plus chemotherapy for PD-L1-positive metastatic TNBC (CPS ≥10) based on KEYNOTE-355 data — demonstrating how a failed monotherapy trial informed a successful combination pivot.',
        indication: 'Metastatic TNBC (PD-L1 CPS ≥10) — combination',
        evidenceIds: ['ev-001'],
        confidence: 'primary',
        importance: 'medium',
      },
      {
        id: 'he-006',
        year: 2020,
        date: '2020-06-16',
        title: 'Tumor-agnostic approval — TMB-high solid tumors',
        type: 'indication_expansion',
        summary:
          'FDA granted accelerated approval for pembrolizumab in unresectable or metastatic TMB-high (≥10 mutations/Mb) solid tumors that progressed following prior treatment. This tissue-agnostic approval — the second after the 2017 MSI-H approval — marked a paradigm shift from histology-based to biomarker-based oncology.',
        indication: 'TMB-high solid tumors — tumor agnostic',
        evidenceIds: ['ev-001'],
        confidence: 'primary',
        importance: 'high',
      },
    ],
  },

  agentRun: {
    runId: 'fixture-keytruda-001',
    status: 'complete',
    sourcesChecked: 14,
    steps: [
      {
        id: 'step-01',
        label: 'Drug identity resolved',
        status: 'complete',
        details: 'Pembrolizumab (Keytruda) — Merck · PD-1 inhibitor · Approved',
        durationMs: 340,
      },
      {
        id: 'step-02',
        label: 'FDA label retrieved',
        status: 'complete',
        details: 'KEYTRUDA Prescribing Information — October 2023 (20+ indications)',
        durationMs: 820,
      },
      {
        id: 'step-03',
        label: '487 clinical trial records discovered',
        status: 'complete',
        details: 'ClinicalTrials.gov — 487 studies involving pembrolizumab',
        durationMs: 1200,
      },
      {
        id: 'step-04',
        label: 'Major development events extracted',
        status: 'complete',
        details: '6 key milestones identified including 2 approvals, 1 setback, 1 expansion',
        durationMs: 1800,
      },
      {
        id: 'step-05',
        label: '2 setbacks investigated — Setback Investigator × 2',
        status: 'complete',
        details: 'Parallel subagent investigation of failed/terminated trials',
        durationMs: 3200,
      },
      {
        id: 'step-05a',
        label: 'KEYNOTE-119 investigation',
        status: 'complete',
        details: 'Public explanation found — Merck press release + ClinicalTrials.gov results',
        durationMs: 2100,
        parentStepId: 'step-05',
      },
      {
        id: 'step-06',
        label: '7 mechanism neighbors identified — 3 subagents',
        status: 'complete',
        details: 'Target subagent: 3 PD-1 inhibitors · Mechanism: 2 PD-L1 · Indication: 2 shared',
        durationMs: 2800,
      },
      {
        id: 'step-06a',
        label: 'Target neighbor subagent',
        status: 'complete',
        details: 'Nivolumab, Cemiplimab, Dostarlimab — same PD-1 target',
        durationMs: 900,
        parentStepId: 'step-06',
      },
      {
        id: 'step-06b',
        label: 'Mechanism neighbor subagent',
        status: 'complete',
        details: 'Atezolizumab, Durvalumab — PD-L1 pathway',
        durationMs: 780,
        parentStepId: 'step-06',
      },
      {
        id: 'step-06c',
        label: 'Indication neighbor subagent',
        status: 'complete',
        details: 'Ipilimumab — shared oncology indications',
        durationMs: 820,
        parentStepId: 'step-06',
      },
      {
        id: 'step-07',
        label: '14 supporting evidence sources checked',
        status: 'complete',
        details: 'FDA, ClinicalTrials.gov, Merck IR, NEJM, conference reports',
        durationMs: 1400,
      },
    ],
  },
}

const FIXTURES: Record<string, DrugDossier> = {
  keytruda: keytruda,
  pembrolizumab: keytruda,
  'keytruda-pembrolizumab': keytruda,
}

export function getDossier(slug: string): DrugDossier | null {
  const key = slug.toLowerCase().replace(/-+/g, '-').replace(/^-|-$/g, '')
  return FIXTURES[key] ?? FIXTURES[key.replace(/-/g, '')] ?? null
}
